#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# Could also configure this in django settings but makes more sense to have in the wider environment
export CELERY_BROKER_URL="${REDIS_URL}"

postgres_ready() {
python << END
import sys

import psycopg2

try:
    psycopg2.connect("${DATABASE_URL}")
except psycopg2.OperationalError:
    sys.exit(-1)
sys.exit(0)

END
}
until postgres_ready; do
  >&2 echo 'Waiting for Postgres to become available...'
  sleep 1
done
>&2 echo 'Postgres is available'

exec "$@"
