language: python
python: "3.6"
cache:
  pip: true
  directories:
    - node_modules

dist: trusty
sudo: false

services:
  - postgresql

addons:
  postgresql: "11.3"

env:
  global:
    - DJANGO_SETTINGS_MODULE=planex.settings.test
    - DATABASE_URL=postgres://postgres@localhost/travis_ci_test
    - CFG_SECRET_KEY=iamnotsosecret
    - CFG_ALLOWED_HOSTS=localhost
    # TEST_GOOGLE_ANALYTICS_VIEW_ID
    - secure: "ocRCzGXixU2hWvhWTDueG9D0sI6I22HR9z4m790fOKgodyTEEGANl8Kv4gcGyrLZ1FI+gQ3nG/7d52usjWmr33+bbU7aNL4q6sqagLT6STV3vyQniOGljpK0Ic5eWtKlds2rISQkJKCovjgNU+JcMow+o+6PZdjSZBzep8pyVO7Vb36kBZgT5+SedPdgDAvr0z7gNdSRNU4bnVFZL+xgPgYTBLwLrJpHO8arf3DExNjZ/Rks+XoWjezjQcbUqjA1WMRoqNiB8hyxKRBkS+ewrAFxMAcCJ2cc04hwZ4zGAmcQgtmJjek7PKgrnENGzSB8EEUIv86/xmGjIxfWP415bRGNGMGZDiAGi1EZ9f6JTrf8ouoF+wjgQavI2lw9C+RMb/XoGDd8iScbyZtzZoB7PqAJhBWke/jCshH5Ovz4nFvMF5cuXGQV5iAsm0le+6VvfbTSebOqWe1FMtdysgsircnre7mDkp1rbnUqEGzPfaDdQyBSm7vUcgRmrKYSy2MwpXUMRrXgx7wRBtU8L7dsIzIZGoNDNSArhGfVcjJt9GuOVClj5vhl2CyCPAXTy/okdMPyHeynlUyuAVOgKo41TS7ZpQZS5POaUdjfSQG4mS4tZSnrv2EOV9rs4HZPzGEm/Eoc02L8FZSS+oD27max6fu2FiGAoZzL5tdjN5PbIhM="
    # KOMBU_FERNET_KEY
    - secure: "tniBepHdnHXQk/DQPh1qLEvhn2OHQjWSZ5Rfmh9TPcbxU5nWcTlfPjAKhWOCPyqhyHesBiZ1VUeg/g9RuzTgxk+R5K7RW6tk9HRJRMDluqgyCRtM4Euxm77voIM9Y85R0Jlcu6ZQiHSdamTQkMdVtXgQGYqV4SClzMp4fVwAWZx4bL1U52f3FGReX2DbDL1FjRnL09EXavVvtA7YhxM6qKy7ktVlWNrhWWw6fqy3+3Vxe7BYaOxK9mCdIHAZoRNMlsx4xmi7YgkUQEAThRwnWuGolbjbSQwnfkG2x9iESGY12NtYM/P4Qp5BuCQ8EvwXwzKjV7Y2Pm5fx5SQ7cPdprKCzxE5rQDkXWxh4uGhZVKgMNYYdJKaYTqGuYJ/aySIdBz6IcxALDXoZsmBlEgxtER2iZOBN2sBxfM+stHwiAb1bWPsyzMWqbC6AZTRjEEX+tsu2X9c4bDiN60QWuFHp1uwyxWreYG8X/9MrU/CWwKP0H1LAzV/jDaFfbGKKh31IyJtY4n55x/w9o4unYJbHJkbHsetXRlIk3HvUHGRUHMs4PJZ+H4j5fUKFrFq/3M4+ip3ETalJXz7WdL+2HgOUOE4CPmXKMJOFHoE3zwwHlgHkzuamFn5xMlY3Ts3vE23dB6FtJJ6KZ88TMh4NdqNYCtgG+YXmJLYcFircx4uW+g="

before_install:
  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-11 postgresql-client-11
  - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
  - sudo service postgresql restart 11
  - openssl aes-256-cbc -K $encrypted_c2f71745af71_key -iv $encrypted_c2f71745af71_iv -in .travis-gcp-test-account.enc -out .travis-gcp-test-account.json -d

install:
  - pip install codecov
  - pip install wheel
  - pip install -r requirements.txt
  - pip install flake8
  - pip install isort

before_script:
  - psql --version
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - flake8 planex
  - isort --check-only --diff --recursive planex
  - python manage.py check
  - python manage.py makemigrations --check
  - python manage.py migrate --noinput
  - python manage.py collectstatic --noinput
  - coverage run manage.py test planex.test

after_success:
  - coverage xml && codecov -f coverage.xml --commit=$TRAVIS_COMMIT
