# Generated by Django 2.2.14 on 2020-11-07 10:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wagtailmenus", "0023_remove_use_specific"),
        ("wagtailsearchpromotions", "0002_capitalizeverbose"),
        ("wagtailforms", "0004_add_verbose_name_plural"),
        ("wagtailredirects", "0006_redirect_increase_max_length"),
        ("cms_core", "0002_themesettings"),
        ("wagtailcore", "0045_assign_unlock_grouppagepermission"),
        ("cms_site", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="SitePage", new_name="SectionsPage",),
    ]
